List<String> futoDepartments = [
  "Agricultural & Bioresources Engineering",
  "Agricultural Economics",
  "Agricultural Extension",
  "Anatomy",
  "Animal Science Technology",
  "Architecture",
  "Biochemistry",
  "Biological Sciences",
  "Biomedical Technology",
  "Biotechnology",
  "Building Technology",
  "Chemical Engineering",
  "Chemistry",
  "Science Laboratory Technology",
  "Civil Engineering",
  "Computer Science",
  "Crop Science Technology",
  "Cyber Security",
  "Dental Technology",
  "Electrical And Electronics Engineering",
  "Environmental Technology",
  "Financial Management Technology",
  "Fisheries & Aquaculture Technology",
  "Food Science & Technology",
  "Forestry & Wildlife Technology",
  "Geology",
  "Information Management Technology",
  "Information Technology",
  "Management Technology",
  "Maritime Management Technology",
  "Material & Metallurgical Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Microbiology",
  "Optometry",
  "Petroleum Engineering",
  "Physics",
  "Physiology",
  "Polymer & Textile Engineering",
  "Project Management Technology",
  "Prosthesis and Orthopedics",
  "Public Health Technology",
  "Quantity Surveying",
  "Science Laboratory Technology",
  "Software Engineering",
  "Soil Science Technology",
  "Statistics",
  "Surveying & Geoinformatics",
  "Transport Management Technology",
  "Urban & Regional Planning"
];
