List<String> palmDepartments = [
  "Accountancy / Accounting",
  "Animal and Environmental Biology",
  "Banking and Finance",
  "Biochemistry",
  "Biology",
  "Business Administration",
  "Chemistry",
  "Computer Science",
  "Economics",
  "English and Literary Studies",
  "Entrepreneurship",
  "History and International Studies",
  "Industrial Relations and Personnel Management",
  "Linguistics",
  "Marketing",
  "Mathematics",
  "Microbiology",
  "Philosophy",
  "Physics",
  "Physics Electronics",
  "Plant Science and Biotechnology",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Statistics"
];
