package com.wizardom.backend.domain.university.department.config;

import java.util.Arrays;
import java.util.List;

public class DepartmentConfig {

    public static final List<String> futoDepartments =
            Arrays.asList(
            "Agricultural & Bioresources Engineering",
            "Agricultural Economics",
            "Agricultural Extension",
            "Anatomy",
            "Animal Science Technology",
            "Architecture",
            "Biochemistry",
            "Biological Sciences",
            "Biomedical Technology",
            "Biotechnology",
            "Building Technology",
            "Chemical Engineering",
            "Chemistry",
            "Science Laboratory Technology",
            "Civil Engineering",
            "Computer Science",
            "Crop Science Technology",
            "Cyber Security",
            "Dental Technology",
            "Electrical And Electronics Engineering",
            "Environmental Technology",
            "Financial Management Technology",
            "Fisheries & Aquaculture Technology",
            "Food Science & Technology",
            "Forestry & Wildlife Technology",
            "Geology",
            "Information Management Technology",
            "Information Technology",
            "Management Technology",
            "Maritime Management Technology",
            "Material & Metallurgical Engineering",
            "Mathematics",
            "Mechanical Engineering",
            "Mechatronics Engineering",
            "Microbiology",
            "Optometry",
            "Petroleum Engineering",
            "Physics",
            "Physiology",
            "Polymer & Textile Engineering",
            "Project Management Technology",
            "Prosthesis and Orthopedics",
            "Public Health Technology",
            "Quantity Surveying",
            "Science Laboratory Technology",
            "Software Engineering",
            "Soil Science Technology",
            "Statistics",
            "Surveying & Geoinformatics",
            "Transport Management Technology",
            "Urban & Regional Planning"
    );

    public static final List<String> imsuDepartments = Arrays.asList(
            "Accountancy",
            "Accountancy / Accounting",
            "Agricultural Engineering",
            "Agricultural Science and Education",
            "Agriculture",
            "Animal Science and Fisheries",
            "Architecture",
            "Banking and Finance",
            "Biochemistry",
            "Botany",
            "Building",
            "Chemical Engineering Technology",
            "Chemistry and Industrial Chemistry",
            "Civil Engineering",
            "Computer Science",
            "Crop Science And Biotechnology",
            "Economics",
            "Education Accounting",
            "Education and Biology",
            "Education and Chemistry",
            "Education and Christian Religious Studies",
            "Education and Economics",
            "Education and English Language",
            "Education Fine and Applied Arts",
            "Education and French",
            "Education and Geography",
            "Education and Geography / Physics",
            "Education and Government",
            "Education and History",
            "Education and Igbo",
            "Education and Mathematics",
            "Education and Physics",
            "Education and Religious Studies",
            "Educational / Psychology, Guidance and Counseling",
            "Educational Administration",
            "Educational Foundations and Administration",
            "Electrical / Electronic Engineering",
            "English and Literary Studies",
            "Estate Management",
            "Fine / Applied Art",
            "Food Science and Technology",
            "Forestry And WildLife",
            "French",
            "Geography and Environmental Management",
            "Government And Public Administration",
            "Guidance and Counseling",
            "History and International Studies",
            "Home Economics and Education",
            "Hospitality And Tourism Management",
            "Igbo / Linguistics",
            "Industrial Mathematics",
            "Industrial Microbiology",
            "Industrial Physics",
            "Insurance and Actuarial Science",
            "Land Survey",
            "Library and Information Science",
            "Linguistics",
            "Management Studies",
            "Marketing",
            "Mass Communication",
            "Mathematics",
            "Mechanical Engineering",
            "Medical Laboratory Technology / Science",
            "Microbiology",
            "Nursing / Nursing Science",
            "Nutrition and Dietetics",
            "Philosophy",
            "Physics",
            "Psychology",
            "Public Health",
            "Quantity Surveying",
            "Religious Studies",
            "Sociology",
            "Soil Science",
            "Soil Science and Environmental Management",
            "Statistics",
            "Surveying and Geo - Informatics",
            "Theatre Arts",
            "Urban and Regional Planning",
            "Zoology",
            "Land Surveying",
            "Fine and Applied Arts"
    );

    public static final List<String> palmUniversities=  Arrays.asList(
            "Accountancy / Accounting",
            "Animal and Environmental Biology",
            "Banking and Finance",
            "Biochemistry",
            "Biology",
            "Business Administration",
            "Chemistry",
            "Computer Science",
            "Economics",
            "English and Literary Studies",
            "Entrepreneurship",
            "History and International Studies",
            "Industrial Relations and Personnel Management",
            "Linguistics",
            "Marketing",
            "Mathematics",
            "Microbiology",
            "Philosophy",
            "Physics",
            "Physics Electronics",
            "Plant Science and Biotechnology",
            "Political Science",
            "Psychology",
            "Public Administration",
            "Religious Studies",
            "Sociology",
            "Statistics"
    );
}
